In [1]:
!pip install -U transformers accelerate datasets evaluate rouge_score sacrebleu bert_score sentencepiece -q

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [37]:
import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from datasets import Dataset

from transformers import T5Tokenizer, T5ForConditionalGeneration, DataCollatorForSeq2Seq, Seq2SeqTrainer, Seq2SeqTrainingArguments

from tqdm.auto import tqdm
import evaluate
from dotenv import load_dotenv
load_dotenv()

True

In [38]:
# df = pd.read_csv('/content/drive/MyDrive/t5_tune/two_problems/data/reviews_with_summaries_longer.csv')
df = pd.read_csv('data/reviews_with_summaries_longer.csv')
df.head()

,review,sentiment,review_clean,n_words,summary
0,I don't think I really have any spoilers in he...,positive,I don't think I really have any spoilers in he...,725,The review says this positive Western is easy ...
1,A magical journey concocted by Alexander Korda...,positive,A magical journey concocted by Alexander Korda...,160,The review is very positive because it praises...
2,"What an awesome movie! It was very scary, grea...",positive,"What an awesome movie! It was very scary, grea...",163,"This movie is awesome and very scary, with gre..."
3,I had a heck of a good time viewing this pictu...,positive,I had a heck of a good time viewing this pictu...,206,The reviewer liked the film because the acting...
4,Citizen X tells the real life drama of the sea...,positive,Citizen X tells the real life drama of the sea...,132,Citizen X is a great film that shows a long re...

## Смотрим как сейчас сгенерирует

In [39]:
model_name = "t5-base"

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"


t5_tokenizer = T5Tokenizer.from_pretrained(model_name)
t5_model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)

print(device)

Loading weights:   0%|          | 0/257 [00:00<?, ?it/s]

mps

https://huggingface.co/docs/transformers/model_doc/t5#transformers.T5ForConditionalGeneration

In [ ]:
for i in range(10):
    example = df.iloc[i]

    text = "summarize movie review: " + example["review_clean"]
    true_summary = example["summary"]

    inputs = t5_tokenizer(text, return_tensors="pt").input_ids.to(device)

    with torch.no_grad():
        outputs = t5_model.generate(inputs, max_length=40, min_length=10, num_beams=4, early_stopping=True)

    t5_summary = t5_tokenizer.decode(outputs[0], skip_special_tokens=True)

    print("Reference:")
    print(true_summary)

    print("\nt5 generated:")
    print(t5_summary)
    print('-------------------------------')
    print('\n\n')

Reference:
The review says this positive Western is easy to enjoy for everyone, with very likable characters, funny scenes, a good story, beautiful music and scenery, and exciting action.

t5 generated:
"Shadows in the Dust" is one of my favorite movies . it has a good story, very engaging characters, beautiful scenery and plenty of action balanced with humor and
-------------------------------



Reference:
The review is very positive because it praises the magical story, beautiful Technicolor, a great Miklós Rózsa music score, strong acting, and clear vivid DVD colors.

t5 generated:
a magical journey concocted by Alexander Korda and Michael Powell . some of the most ravishing early Technicolor, a SUBLIME and a
-------------------------------



Reference:
This movie is awesome and very scary, with great acting, a well-written story and twists, interesting characters, good direction, and a surprise ending, so I highly recommend it.

t5 generated:
this is one popcorn horror flick that may not be appealing to non-horror fans . but it is still (nonetheless) one of the best thrillers out there
-------------------------------



Reference:
The reviewer liked the film because the acting and dialogue are good and it has smart questions about science, and the sax music is bright, but it is also cheaply made and sleazy.

t5 generated:
the film is undeniably cheaply-made with its cardboard sets, limited settings, and creative scientific props . the scripting though is very good and the dialogue is fantastic for
-------------------------------



Reference:
Citizen X is a great film that shows a long real-life hunt for the serial killer, with strong performances by Stephen Rea and Donald Sutherland, and political help that let him continue.

t5 generated:
"Citizen X" tells the real life drama of the search for a serial killer . the film shows how politics may have helped the killer to continue his rampage
-------------------------------



Reference:
Eddie Murphy’s HBO stand up show is very funny because his great impressions and characters, like Mr. T and Michael Jackson, made me laugh a lot.

t5 generated:
"eddie Murphy Delirious" is his best stand up performance next to "Eddie Murphy Raw"
-------------------------------



Reference:
The film has a weak start, but the middle is solid and the finish is fantastic, and I enjoyed Pegg’s different role and Bridges’ acting, though the early awkward humor upset me.

t5 generated:
reviewer: "weak start, solid middle, fantastic finish" "i just wish I had come in 40 minutes late, and missed the beginning," he says .
-------------------------------



Reference:
The film is very entertaining, with strong humor and a clear message about big changes like Black Power and Vietnam, and it still feels engrossing as a good period piece.

t5 generated:
this film had about everything one could wish when viewing it originally, at the end of the 1960's decade . it provided a contemporary view of the many changes which had occurred during that
-------------------------------



Reference:
The review is very positive, saying the hardcore musical Alice is amusing, tuneful and energetic, with great performances from the large cast and mainly strong lead actors.

t5 generated:
this is the uncut hardcore, musical Alice! it works too with a large energetic cast seemingly enjoying themselves to the hilt . there are a couple of slightly off
-------------------------------



Reference:
The acting is mostly very good, with great performances by Jude Law and strong cinematography, plus a powerful love story, beautiful music, and excellent direction.

t5 generated:
the only actor that blew me away with his performance was Jude Law as Harlen Maguire . cinematography is what made the movie a masterpiece . the screen Writing is
-------------------------------

## Пробуем дообучить

In [41]:
df['n_words'].describe()

count    2000.000000
mean      246.281000
std       164.055073
min       100.000000
25%       137.750000
50%       186.000000
75%       296.000000
max      1808.000000
Name: n_words, dtype: float64

In [42]:
df['summary_length'] = df['summary'].apply(lambda x: len(x.split()))
df['summary_length'].describe()

count    2000.000000
mean       28.718500
std         2.684001
min        19.000000
25%        27.000000
50%        29.000000
75%        31.000000
max        38.000000
Name: summary_length, dtype: float64

In [43]:
df = df[df['summary_length'] > 3]
df['summary_length'].describe()

count    2000.000000
mean       28.718500
std         2.684001
min        19.000000
25%        27.000000
50%        29.000000
75%        31.000000
max        38.000000
Name: summary_length, dtype: float64

In [44]:
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df["sentiment"])

train_df.shape, test_df.shape

((1600, 6), (400, 6))

## Учим

In [45]:
prefix = "summarize movie review: "

train_df["input_text"] = prefix + train_df["review_clean"]
test_df["input_text"] = prefix + test_df["review_clean"]

In [46]:
train_dataset = Dataset.from_pandas(train_df[["input_text", "summary"]])
test_dataset = Dataset.from_pandas(test_df[["input_text", "summary"]])

In [ ]:
def preprocess(examples):
    model_inputs = t5_tokenizer(examples["input_text"], max_length=600, padding="max_length", truncation=True)

    labels = t5_tokenizer(examples["summary"], max_length=60, padding="max_length", truncation=True)

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

https://github.com/hse-ds/iad-deep-learning/blob/master/2025/homeworks/homework_04.ipynb

https://habr.com/ru/articles/762140/

In [48]:
tokenized_dataset = train_dataset.map(preprocess)
test_dataset = test_dataset.map(preprocess)
# tokenized_dataset.set_format("torch")
# test_dataset.set_format("torch")

Map:   0%|          | 0/1600 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

In [49]:
data_collator = DataCollatorForSeq2Seq(tokenizer=t5_tokenizer, model=t5_model)

In [50]:
rouge_metric = evaluate.load("rouge")
bleu_metric = evaluate.load("sacrebleu")
bertscore_metric = evaluate.load("bertscore")

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

In [51]:
def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [label.strip() for label in labels]

    preds = [pred if pred != "" else "empty" for pred in preds]

    return preds, labels

In [ ]:
def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]

    decoded_preds = t5_tokenizer.batch_decode(preds, skip_special_tokens=True)

    labels = np.where(labels != -100, labels, t5_tokenizer.pad_token_id)

    decoded_labels = t5_tokenizer.batch_decode(labels, skip_special_tokens=True)

    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    bleu_result = bleu_metric.compute(predictions=decoded_preds, references=[[label] for label in decoded_labels])
    rouge_result = rouge_metric.compute(predictions=decoded_preds, references=decoded_labels)
    bertscore_result = bertscore_metric.compute(predictions=decoded_preds, references=decoded_labels, lang="en")

    prediction_lens = [np.count_nonzero(pred != t5_tokenizer.pad_token_id) for pred in preds]

    result = {
        "bleu": bleu_result["score"],
        "rouge1": rouge_result["rouge1"],
        "rouge2": rouge_result["rouge2"],
        "rougeL": rouge_result["rougeL"],
        "bertscore_precision": np.mean(bertscore_result["precision"]),
        "bertscore_recall": np.mean(bertscore_result["recall"]),
        "bertscore_f1": np.mean(bertscore_result["f1"]),
        "gen_len": np.mean(prediction_lens),
    }

    return {k: round(v, 4) for k, v in result.items()}

In [ ]:
new_model = "t5_base"

training_args = Seq2SeqTrainingArguments(
    output_dir=new_model,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    num_train_epochs=10,
    predict_with_generate=True,
    generation_max_length=60,
    fp16=True,
    push_to_hub=False
)

trainer = Seq2SeqTrainer(
    model=t5_model,
    args=training_args,
    train_dataset=tokenized_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

In [ ]:
test_metrics = trainer.evaluate(eval_dataset=test_dataset)

test_metrics

## Инферим немного

In [54]:
model_path = "models/t5_base_summarizer"


t5_tokenizer = T5Tokenizer.from_pretrained(model_path)
t5_model = T5ForConditionalGeneration.from_pretrained(model_path).to(device)

Loading weights:   0%|          | 0/257 [00:00<?, ?it/s]

### Base tuned

In [ ]:
for i in range(10):
    example = df.iloc[1800 + i]

    text = "summarize movie review: " + example["review_clean"]
    true_summary = example["summary"]

    inputs = t5_tokenizer(text, return_tensors="pt").input_ids.to(device)

    with torch.no_grad():
        outputs = t5_model.generate(inputs, max_length=60, min_length=10, num_beams=4, early_stopping=True)

    t5_summary = t5_tokenizer.decode(outputs[0], skip_special_tokens=True)

    print("Reference:")
    print(true_summary)

    print("\nt5 generated:")
    print(t5_summary)
    print('-------------------------------')
    print('\n\n')

Reference:
The review is very negative, saying the show is a bad sketch and tries too hard to be funny, with weak writing and an unfunny host, wasting viewers’ time.

t5 generated:
The reviewer says the show is a crap show, with hard sketches, no funny sketches, and a no-talent host, so they give it a fair shot.
-------------------------------



Reference:
The review says this sixth horror movie is boring and has a slow pace, dumb ending, bland acting, and unpleasant revelations, while the mirror causes the strange but not exciting events.

t5 generated:
The review is negative because the horror is dull and lifeless, with ropey acting and Ross Partridge’s huge hair not helping matters.
-------------------------------



Reference:
The reviewer hates the film because it has unrealistic drug-life stereotypes, a confusing shoe quest with no clear plot, and characters feel too outrageous for real life.

t5 generated:
The reviewer hated the film because it has shallow Hollywood fare and stereotypical caricatures, too many outrageous characters, and no discernable plot, so they decided to end it.
-------------------------------



Reference:
The review is very negative: the film was boring, the CGI ship and creature looked bad, and the writer says to avoid it and not buy the DVD, with a shame about who funded it.

t5 generated:
The reviewer says the sci-fi movie was bad, the cgi ship was bad, the creature looked like a 5 foot bat, and the cgi ship was bad.
-------------------------------



Reference:
The reviewer says the film is silly and sometimes fun, but it has bad acting, a dull and repetitive monster, too few monster moments, and it copies an older movie.

t5 generated:
The review is negative because the alien monster is dull, the acting is awful and amateurish, and the action is repetitive and predictable.
-------------------------------



Reference:
The review says “Bubble” is realistic and quietly portrays small-town life, but it feels empty, lacks payoffs, and the audience’s reactions are smug and judgmental, so the film disappoints.

t5 generated:
The review says “Bubble” is a realistic and understated portrayal of small town life, with no payoffs, and the audience feels smug and judgmental.
-------------------------------



Reference:
The film is only somewhat fun for fans of bad movies, but the plot is very bad, with little to enjoy except some 1970s fashion and a few nude scenes.

t5 generated:
The review is negative because it says the movie is not attractive for fans of bad entertainment, has a bad plot, and has few bare breasts.
-------------------------------



Reference:
The film is not good because the story choices are very poor, the dialogue feels weak, and there are too many music montage scenes instead of a clear, well-developed plot.

t5 generated:
The review is negative because the production is poor, the story is not fully realized, the story is not well developed, and the music montage makes it difficult to follow.
-------------------------------



Reference:
The reviewer says Inuyasha is overrated because it has no real story, repeats the same filler scenes and jokes, includes suggestive sexual harassment, and has annoying reused music and bad games.

t5 generated:
The review says Inuyasha is not a good anime because it has no story, no plot, repeating same stories, bad videogames, and annoying music, so it is overrated.
-------------------------------



Reference:
The review says the story of a scared boy is unbelievable, and even good actors like Macaulay Culkin cannot make it better.

t5 generated:
The review says the story is unbelievable and even good actors could not make it better.
-------------------------------

### Small tuned

In [56]:
model_path = "models/t5_small_summarizer"

t5_tokenizer = T5Tokenizer.from_pretrained(model_path)
t5_model = T5ForConditionalGeneration.from_pretrained(model_path).to(device)

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

In [ ]:
for i in range(10):
    example = df.iloc[1800 + i]

    text = "summarize movie review: " + example["review_clean"]
    true_summary = example["summary"]

    inputs = t5_tokenizer(text, return_tensors="pt").input_ids.to(device)

    with torch.no_grad():
        outputs = t5_model.generate(inputs, max_length=60, min_length=10, num_beams=4, early_stopping=True)

    t5_summary = t5_tokenizer.decode(outputs[0], skip_special_tokens=True)

    print("Reference:")
    print(true_summary)

    print("\nt5 generated:")
    print(t5_summary)
    print('-------------------------------')
    print('\n\n')

Reference:
The review is very negative, saying the show is a bad sketch and tries too hard to be funny, with weak writing and an unfunny host, wasting viewers’ time.

t5 generated:
The reviewer says the show is a crap show because Spike is not funny, his sketches are hard, and the writers are struggling to write material for a no-talent host.
-------------------------------

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (816 > 512). Running this sequence through the model will result in indexing errors

Reference:
The review says this sixth horror movie is boring and has a slow pace, dumb ending, bland acting, and unpleasant revelations, while the mirror causes the strange but not exciting events.

t5 generated:
The review is negative because the horror is dull and lifeless, the acting and hairdo Ross Partridge’s hair are not helping matters.
-------------------------------



Reference:
The reviewer hates the film because it has unrealistic drug-life stereotypes, a confusing shoe quest with no clear plot, and characters feel too outrageous for real life.

t5 generated:
The reviewer says the film is very bad because of its shallow Hollywood fare and stereotypical caricatures, realism, and a lack of shoes, so they decided to end it.
-------------------------------



Reference:
The review is very negative: the film was boring, the CGI ship and creature looked bad, and the writer says to avoid it and not buy the DVD, with a shame about who funded it.

t5 generated:
The review says the movie is bad because the cgi ship is bad, the creature looks like a 5 foot bat, and the DVD is not worth buying.
-------------------------------



Reference:
The reviewer says the film is silly and sometimes fun, but it has bad acting, a dull and repetitive monster, too few monster moments, and it copies an older movie.

t5 generated:
The review says NIGHTBEAST is very boring and boring, with dull acting, repetitive attacks and suspense, and it is not entertaining, so it is worth watching.
-------------------------------



Reference:
The review says “Bubble” is realistic and quietly portrays small-town life, but it feels empty, lacks payoffs, and the audience’s reactions are smug and judgmental, so the film disappoints.

t5 generated:
The review says “Bubble” is a realistic, understated, realistic small town life portrayal, with smug and judgmental reactions, and it is worth considering.
-------------------------------



Reference:
The film is only somewhat fun for fans of bad movies, but the plot is very bad, with little to enjoy except some 1970s fashion and a few nude scenes.

t5 generated:
The review says the film is very bad, with poor fashions, furniture, attitudes, and great women’s lib moments, but the plot is awful, and the audience has few bare breasts.
-------------------------------



Reference:
The film is not good because the story choices are very poor, the dialogue feels weak, and there are too many music montage scenes instead of a clear, well-developed plot.

t5 generated:
The review says the film is inconsequential, with poor choices, poor screenplays, and a weak story about Eddy’s death, so it is not good for you.
-------------------------------



Reference:
The reviewer says Inuyasha is overrated because it has no real story, repeats the same filler scenes and jokes, includes suggestive sexual harassment, and has annoying reused music and bad games.

t5 generated:
The reviewer says Inuyasha is overrated because it has no story line, no plot, and more side stories and fillers, and it has no funny sexual harassment.
-------------------------------



Reference:
The review says the story of a scared boy is unbelievable, and even good actors like Macaulay Culkin cannot make it better.

t5 generated:
The review says the movie is unbelievable and the story is unbelievable, even good actors like Macaulay Culkin could not make it better than it is.
-------------------------------

In [63]:
def eval_(model_path, test_df):
    tokenizer = T5Tokenizer.from_pretrained(model_path)
    model = T5ForConditionalGeneration.from_pretrained(model_path).to(device)
    model.eval()

    t5_summaries = []
    reference_summaries = []
    prediction_lens = []

    for i in tqdm(range(len(test_df))):

        true_summary = test_df.iloc[i]["summary"]
        input_text = test_df.iloc[i]["input_text"]

        inputs = tokenizer(input_text, return_tensors="pt", max_length=512, truncation=True).input_ids.to(device)

        with torch.no_grad():
            outputs = model.generate(inputs, max_length=60, min_length=10, num_beams=4, early_stopping=True)

        t5_summary = tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

        t5_summaries.append(t5_summary)
        reference_summaries.append(true_summary)
        prediction_lens.append(np.count_nonzero(outputs[0].cpu().numpy() != tokenizer.pad_token_id))

    bleu_result = bleu_metric.compute(predictions=t5_summaries, references=[[label] for label in reference_summaries])
    rouge_result = rouge_metric.compute(predictions=t5_summaries, references=reference_summaries)
    bertscore_result = bertscore_metric.compute(predictions=t5_summaries, references=reference_summaries, lang="en")

    result = {
        "bleu": bleu_result["score"],
        "rouge1": rouge_result["rouge1"],
        "rouge2": rouge_result["rouge2"],
        "rougeL": rouge_result["rougeL"],
        "bertscore_precision": np.mean(bertscore_result["precision"]),
        "bertscore_recall": np.mean(bertscore_result["recall"]),
        "bertscore_f1": np.mean(bertscore_result["f1"]),
        "gen_len": np.mean(prediction_lens),
    }

    return {k: round(float(v), 4) for k, v in result.items()}

In [64]:
small_metrics = eval_("models/t5_small_summarizer", test_df)
base_metrics = eval_("models/t5_base_summarizer", test_df)

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

  0%|          | 0/400 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/257 [00:00<?, ?it/s]

  0%|          | 0/400 [00:00<?, ?it/s]

In [65]:
comparison_df = pd.DataFrame([{"model": "T5-small fine-tuned", **small_metrics}, {"model": "T5-base fine-tuned", **base_metrics}])
comparison_df

,model,bleu,rouge1,rouge2,rougeL,bertscore_precision,bertscore_recall,bertscore_f1,gen_len
0,T5-small fine-tuned,14.1498,0.4412,0.1823,0.3544,0.9050,0.9076,0.9062,42.775
1,T5-base fine-tuned,15.5086,0.4607,0.1934,0.3696,0.9114,0.9125,0.9119,42.020

## Смотрим базовые модели

In [61]:
small_zero_metrics = eval_("t5-small", test_df)
base_zero_metrics = eval_("t5-base", test_df)

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

  0%|          | 0/400 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/257 [00:00<?, ?it/s]

  0%|          | 0/400 [00:00<?, ?it/s]

WARNING:sacrebleu:That's 100 lines that end in a tokenized period ('.')
WARNING:sacrebleu:It looks like you forgot to detokenize your test data, which may hurt your score.
WARNING:sacrebleu:If you insist your data is detokenized, or don't care, you can suppress this message with the `force` parameter.

In [62]:
comparison_df = pd.DataFrame([{"model": "T5-small", **small_zero_metrics}, {"model": "T5-base", **base_zero_metrics}])
comparison_df

,model,bleu,rouge1,rouge2,rougeL,bertscore_precision,bertscore_recall,bertscore_f1,gen_len
0,T5-small,3.5236,0.2639,0.0654,0.1904,0.8574,0.8723,0.8647,53.1500
1,T5-base,3.4563,0.2798,0.0741,0.1988,0.8522,0.8748,0.8633,52.4925